const $=id=>document.getElementById(id);
const status=msg=>$('status').textContent=msg;
const enc=new TextEncoder(),dec=new TextDecoder();
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a)));
const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function deriveKey(pass,salt){const base=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function encryptProfile(profile,pass){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const key=await deriveKey(pass,salt);const data=enc.encode(JSON.stringify(profile));const ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,data);return {v:1,alg:'AES-GCM',kdf:'PBKDF2-SHA256',iterations:250000,salt:b64(salt),iv:b64(iv),ciphertext:b64(ct)};}
async function decryptProfile(box,pass){if(!box||box.v!==1)throw new Error('Invalid encrypted profile');const salt=unb64(box.salt),iv=unb64(box.iv),key=await deriveKey(pass,salt);const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,unb64(box.ciphertext));const p=JSON.parse(dec.decode(pt));if(!p||typeof p!=='object'||Array.isArray(p))throw new Error('Invalid profile');return p;}
async function getBox(){return (await chrome.storage.local.get('beroppEncryptedProfile')).beroppEncryptedProfile||null}
$('import').addEventListener('click',async()=>{const file=$('profileFile').files[0],pass=$('passphrase').value;if(!file){status('Choose your exported profile JSON first.');return}if(pass.length<10){status('Use a passphrase with at least 10 characters.');return}try{const p=JSON.parse(await file.text());if(!p||typeof p!=='object'||Array.isArray(p))throw new Error('Invalid profile');const box=await encryptProfile(p,pass);await chrome.storage.local.set({beroppEncryptedProfile:box});await chrome.storage.local.remove('beroppProfile');$('passphrase').value='';status('🔐 Profile encrypted and stored locally.');}catch(e){status('❌ Could not import/encrypt this profile.');}});
$('fill').addEventListener('click',async()=>{const box=await getBox(),pass=$('passphrase').value;if(!box){status('Import and encrypt a profile first.');return}if(pass.length<10){status('Enter your encryption passphrase.');return}const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id){status('No active page found.');return}try{const p=await decryptProfile(box,pass);const result=await chrome.tabs.sendMessage(tab.id,{type:'BEROPP_FILL',profile:p});const missing=result?.unmatchedFields||[];status(`Filled: ${result?.filled||0} · Not matched: ${missing.length}`);$('missing').textContent=missing.length?`Not matched: ${missing.join(', ')}`:'All available profile fields were matched.';$('passphrase').value='';}catch(e){$('passphrase').value='';status(e?.name==='OperationError'?'❌ Wrong passphrase.':'This page does not allow autofill. Try a normal website tab.');$('missing').textContent='';}});
$('clear').addEventListener('click',async()=>{await chrome.storage.local.remove(['beroppEncryptedProfile','beroppProfile']);$('passphrase').value='';status('Encrypted extension profile deleted.');$('missing').textContent='';});
(async()=>{if(await getBox())status('🔐 Encrypted profile ready. Enter your passphrase to fill a form.');})();